definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
host: 195.2.80.162:80
info:
  contact: {}
  description: API Server for povarenokApp
  title: Povarenok :)
  version: "1.0"
paths:
  /recipe/show:
    get:
      consumes:
      - application/json
      operationId: getRecipe
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - Recipe
  /recipes:
    get:
      consumes:
      - application/json
      description: |-
        category=1 - Свежие рецепты
        category=2 - Бульоны и супы
        category=6 - Горячие блюда
        category=12 - Салаты
        category=15 - Закуски
        category=25 - Выпечка
        category=30 - Десерты
        category=23 - Соусы
      operationId: getPreview
      parameters:
      - description: category
        in: query
        name: category
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - Preview
swagger: "2.0"
