basePath: /
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
host: 195.2.80.162:80
info:
  contact: {}
  description: API Server for scrapingApp
  title: Povarenok API
  version: "1.0"
paths:
  /recipe/show:
    get:
      consumes:
      - application/json
      description: Get recipe
      operationId: getRecipe
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Recipe
      tags:
      - recipe
  /recipes:
    get:
      consumes:
      - application/json
      description: Get preview
      operationId: getPreview
      parameters:
      - description: category
        in: query
        name: category
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Preview
      tags:
      - Preview
swagger: "2.0"
